### PR TITLE
Clarify dependencies according to standards [WIP].

### PR DESCRIPTION
**Pull request by jpic**
This is a followup for discussion around dependencies and coherence in #17.

### CODE REVIEW

**Comment by gravyboat** [comment]
I'm also noting https://github.com/saltstack-formulas/jenkins-formula/issues/3 here since someone mentioned it and then we can get that closed. @jpic Do you want to write a state that installs nginx locally within the jenkins formula for users or do you think the readme will be sufficient?

**Comment by jpic** [comment]
If we add a state installing nginx locally within jenkins.nginx, would we still be including nginx in jenkins.nginx ? In that case, shouldn't we be including the jenkins state as well in jenkins.nginx ?

I'd rather leave it to the user, in prevision for when we have something able to pull formulas and dependencies like ansible-galaxy, which relies on dependencies being declared in `meta.yml`.

In my dreams though, we could use pip and virtualenv directly even for saltstack formulas.

What's pretty interresting, is that the above test failed because:

```
[INFO    ] Running state [jenkins] at time 18:14:28.602729
[INFO    ] Executing state user.present for jenkins
[INFO    ] Executing command 'usermod -d /usr/local/jenkins jenkins' in directory '/home/travis'
[ERROR   ] Command 'usermod -d /usr/local/jenkins jenkins' failed with return code: 8
[ERROR   ] output: usermod: user jenkins is currently logged in
[INFO    ] Executing command 'usermod -d /usr/local/jenkins  -m jenkins' in directory '/home/travis'
[ERROR   ] Command 'usermod -d /usr/local/jenkins  -m jenkins' failed with return code: 8
[ERROR   ] output: usermod: user jenkins is currently logged in
[ERROR   ] These values could not be changed: {'home': '/usr/local/jenkins'}
```

I wonder if that's related to this change (nginx included manually rather than at the top of jenkins.nginx). Really interresting.

**Comment by whiteinge** [comment]
@gravyboat Implicit dependencies can be fragile and difficult to juggle. An explicit dependency (via `include`) is far more resilient. Thanks for the mention that this practice is more widespread, I didn't realize that -- we badly need a package-manager-esque tool to bring sanity here.

**Comment by gravyboat** [comment]
@whiteinge Yeah it's been a real problem for a while and it is something that I don't have a great solution for. It's tough because some apps you need another dependency, while others you don't and I'm not sure how to address that while remaining friendly to new users.

**Comment by whiteinge** [comment]
There's been good discussion about it on the formulas list and Dave
and myself have a few ideas. I'm leaning toward the Python packages
approach (so long as the actual creation is a one-liner command). It
really just needs time + someone to do the work, I think. :-P

**Comment by jpic** [comment]
On Mon, May 18, 2015 at 10:10 PM, Seth House <notifications@github.com>
wrote:

> There's been good discussion about it on the formulas list and Dave
> and myself have a few ideas. I'm leaning toward the Python packages
> approach (so long as the actual creation is a one-liner command). It
> really just needs time + someone to do the work, I think. :-P
>

Could you paste some link about it ?

Thanks

**Comment by whiteinge** [comment]
https://groups.google.com/d/topic/salt-formulas/2B_7EwgCT7s/discussion

**Comment by jpic** [comment]
Thanks

**Pull request merged**
